
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#influx
influxdb:
  api_version: 2
  ssl: false
  host: 192.168.0.139
  port: 8086
  token: fi90lLS0B3PQV9_cq3NjDjeEybxK_ZYckHCwNBRKBgdhU3IFbzMy-0SoGfyE1xTdS-JAL2VrVs-0ouWiagtlNw==
  organization: d2be80d14f65910b
  bucket: homeassistant_data
sensor:
  - platform: splitwise
    client_id: 'P3bg62zerVaWbUOa6PX4F1813CrOGg77NxANKbYI'
    client_secret: '6kbShCg42dnbuHsEYN2ZRmGeRcpe7bQGs'
