substitutions:
  name: apollo-msr-2-271318
  friendly_name: Apollo MSR-2 Livingroom
packages:
  ApolloAutomation.MSR-2_Factory: github://ApolloAutomation/MSR-2/Integrations/ESPHome/MSR-2_Factory.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: anrP+HPTsgSX5mzQF4SHT1cIs/87pffRM7VLLFOiqn8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
