substitutions:
  name: home-assistant-voice-09b15b
  friendly_name: Home Assistant Voice 09b15b
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: DtsmCubmK7VTPyHr35P1C8Pb/wfMtq5PP44x7YmQQSw=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
