substitutions:
  name: tubeszb-cc2652-poe-2023

packages:
  tubezb.cc2652-poe-2023: github://tube0013/tube_gateways/models/current/tubeszb-cc2652-poe-2023/firmware/esphome/tubeszb-cc2652-poe-2023.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false

api:
  encryption:
    key: HcvUkdOptvDqgMEZW/n2H+yr0DPnJN9ybw2mGORiNQA=

# Enable logging
logger:

ota:
  platform: esphome

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true