esphome:
  name: water2
  friendly_name: water2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "q5j3nZjloGAsdJe4leLaseYqJd+qTvLdiFby6CJl0kQ="

ota:
  - platform: esphome
    password: "ff2dacfcedb0cd40cade27a380fa7c01"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water2 Fallback Hotspot"
    password: "KOkJUo67Yxnd"

i2c:

captive_portal:
    
sensor:
  - platform: qmc5883l
    address: 0x0D
    field_strength_x:
      name: "QMC5883L Field Strength X"
    field_strength_y:
      name: "QMC5883L Field Strength Y"
    field_strength_z:
      name: "QMC5883L Field Strength Z"
    heading:
      name: "QMC5883L Heading"
    temperature:
      name: "QMC5883L Temperature"
      filters:
        - offset: 34.0
    range: 200uT
    oversampling: 512x
    update_interval: 60s